### ISSUE TITLE
Missing setup.py required for pip install

### ISSUE THREAD

**Issue by jezzaaa** [Blake-Haydon/United-Energy-EnergyEasy-API#2]
Hi, just wanting to try this out, to see if I can get it working for Home Assistant. But pip install tells me there's no setup.py file:

```
$ pip install git+https://github.com/Blake-Haydon/United-Energy-EnergyEasy-API.git
Collecting git+https://github.com/Blake-Haydon/United-Energy-EnergyEasy-API.git
  Cloning https://github.com/Blake-Haydon/United-Energy-EnergyEasy-API.git to /tmp/pip-8q3ph8ki-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib64/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-8q3ph8ki-build/setup.py'
```
I tried with pip from python2.7.5 and python3.6.8. Is this something I'm doing wrong?

**Comment by Blake-Haydon** [comment]
Looks like the issue was with an incorrect URL. Try `pip install git+https://github.com/Blake-Haydon/United-Energy-EnergyEasy-API.git#egg=UnitedEnergy` instead. I have updated the README to reflect the change.

**Comment by jezzaaa** [comment]
Thanks very much @Blake-Haydon. I'm no longer getting that error.

I don't know if my environment has changed, or if I'm just showing my newbieness with Git and Python, but I'm now getting a different error, even using the original commandline (without specifying the egg):

```
$ pip install git+https://github.com/Blake-Haydon/United-Energy-EnergyEasy-API.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/Blake-Haydon/United-Energy-EnergyEasy-API.git
  Cloning https://github.com/Blake-Haydon/United-Energy-EnergyEasy-API.git to /tmp/pip-req-build-rib5sepi
  Running command git clone -q https://github.com/Blake-Haydon/United-Energy-EnergyEasy-API.git /tmp/pip-req-build-rib5sepi
  Resolved https://github.com/Blake-Haydon/United-Energy-EnergyEasy-API.git to commit 391443d50104f9bf067d49f44782a257595a7231
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpk53p87p2
       cwd: /tmp/pip-req-build-rib5sepi
  Complete output (16 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/tmp/pip-build-env-liv4m9uo/overlay/lib/python3.6/site-packages/poetry/core/masonry/api.py", line 44, in prepare_metadata_for_build_wheel
      builder = WheelBuilder(poetry)
    File "/tmp/pip-build-env-liv4m9uo/overlay/lib/python3.6/site-packages/poetry/core/masonry/builders/wheel.py", line 58, in __init__
      super(WheelBuilder, self).__init__(poetry, executable=executable)
    File "/tmp/pip-build-env-liv4m9uo/overlay/lib/python3.6/site-packages/poetry/core/masonry/builders/builder.py", line 89, in __init__
      includes=includes,
    File "/tmp/pip-build-env-liv4m9uo/overlay/lib/python3.6/site-packages/poetry/core/masonry/utils/module.py", line 64, in __init__
      "No file/folder found for package {}".format(name)
  poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package unitedenergy
  ----------------------------------------
WARNING: Discarding git+https://github.com/Blake-Haydon/United-Energy-EnergyEasy-API.git. Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpk53p87p2 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpk53p87p2 Check the logs for full command output.

```

**Comment by Blake-Haydon** [comment]
I have had a look at the issue and think I have found a fix @jezzaaa. Try installing the module by running `pip install https://github.com/Blake-Haydon/United-Energy-EnergyEasy-API/blob/master/dist/united_energy-0.3.0-py3-none-any.whl?raw=true`. 

I have been testing in a docker container and it seems to work. Really hope it works for you now.

**Comment by jezzaaa** [comment]
Sorry, still not working for me:
```
$ pip install https://github.com/Blake-Haydon/United-Energy-EnergyEasy-API/blob/master/dist/united_energy-0.3.0-py3-none-any.whl?raw=true
Defaulting to user installation because normal site-packages is not writeable
Collecting united-energy==0.3.0
  Downloading https://github.com/Blake-Haydon/United-Energy-EnergyEasy-API/blob/master/dist/united_energy-0.3.0-py3-none-any.whl?raw=true (2.7 kB)
Collecting requests<3.0.0,>=2.24.0
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
ERROR: Package 'united-energy' requires a different Python: 3.6.8 not in '<4.0,>=3.8'

$ pip --version
pip 21.3.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
```

Does this mean I need to upgrade Python?
```
$ rpm -q python3
python3-3.6.8-18.0.1.el7.x86_64

$ sudo yum update python3
Loaded plugins: langpacks, ulninfo
No packages marked for update
```
If so, I think I'm out of luck with my deployment (an Oracle cloud VM running Oracle Linux 7 aka RHEL/Centos v7). I've done a "yum update" to no avail. Running "yum upgrade" gives me dependency errors that seem to be related to switching to a new release of the OS, and google isn't helping me yet. I figure my only option might be to remove the python3 package and install from source.

**Comment by Blake-Haydon** [comment]
Yeah looks like you require a newer version of python. I'll do some testing on python 3.6 and release an update if it works. That should resolve you problems.

**Comment by jezzaaa** [comment]
I really appreciate your help. But if you find it becomes a bit too difficult, it's also fine to give up and tell me to get over it, because I really should be upgrading my OS. And also, I haven't figured out a way to use this with my Home Assistant installation, because it runs in a docker container and has no CLI-accessible Python at all, so there's a chance I won't be able to make use of your module on-box and will need to cobble together a remote web service or something.

I did manage to get curl to fetch my usage data a few times, but then I started getting authentication errors, so figured I needed to find another way. I'm starting to think it'd be simpler to build one of those LED pulse counters that go onto the meter - I thought a software-only solution would be easier, but it's not turning out that way. *sigh*

**Comment by Blake-Haydon** [comment]
It's all good. Think I've figured it out. Just set the python version to `3.6`. Try running `pip install https://github.com/Blake-Haydon/United-Energy-EnergyEasy-API/blob/master/dist/united_energy-0.3.1-py3-none-any.whl?raw=true`.

If you do get it working I'd love to see it! Good luck!

**Comment by jezzaaa** [comment]
Yes, that's got it installed now. Thanks heaps!

And now, to try to use it in a script...

**Comment by jezzaaa** [comment]
...and that's working also. Calling on_date_data() with today's date shows the energy consumption for today so far. So my plan is to repeatedly call this every hour, extract the previous hour's consumption, and give it to HA. I've yet to learn about HA's plug-in architecture, so that's the next exciting adventure.

With cold nights like we just had here in Melbourne (sub-zero!) I really want to get a handle on my family's energy consumption. Maybe in time for next winter.

Thanks heaps for your work on this module, and your subsequent assistance in getting my environment working.
